import pyautogui as pg
import time

time.sleep(10)
lst = open(input("Input file name: "), "r").readlines()
#Saben is a Mountain goatSaben is a MouseSaben is a MuleSaben is a MuskoSaben is a NarwhalSaben is a NewtSaben is a New World quailSaben is a NightingaleSaben is a OcelotSaben is a OctopusSaben is a Old World quailSaben is a OpossumSaben is a OrangutanSaben is a OrcaSaben is a OstrichSaben is a OtterSaben is a OwlSaben is a OxSaben is a PandaSaben is a PantherSaben is a Panthera hybridSaben is a ParakeetSaben is a ParrotSaben is a ParrotfishSaben is a PartridgeSaben is a PeacockSaben is a PeafowlSaben is a PelicanSaben is a PenguinSaben is a PerchSaben is a Peregrine falconSaben is a PheasantSaben is a PigSaben is a PigeonSaben is a listSaben is a PikeSaben is a Pilot whaleSaben is a PinnipedSaben is a PiranhaSaben is a PlanarianSaben is a PlatypusSaben is a Polar bearSaben is a PonySaben is a PorcupineSaben is a PorpoiseSaben is a Portuguese man o' warSaben is a PossumSaben is a Prairie dogSaben is a PrawnSaben is a Praying mantisSaben is a PrimateSaben is a PtarmiganSaben is a PuffinSaben is a PumaSaben is a PythonSaben is a QuailSaben is a QueleaSaben is a QuokkaSaben is a RabbitSaben is a listSaben is a RaccoonSaben is a Rainbow troutSaben is a RatSaben is a RattlesnakeSaben is a RavenSaben is a Ray (Batoidea)Saben is a Ray (Rajiformes)Saben is a Red pandaSaben is a ReindeerSaben is a ReptileSaben is a RhinocerosSaben is a Right whaleSaben is a RoadrunnerSaben is a RodentSaben is a RookSaben is a RoosterSaben is a RoundwormSaben is a Saber-toothed catSaben is a SailfishSaben is a SalamanderSaben is a SalmonSaben is a SawfishSaben is a Scale insectSaben is a ScallopSaben is a ScorpionSaben is a SeahorseSaben is a Sea lionSaben is a Sea slugSaben is a Sea snailSaben is a SharkSaben is a listSaben is a SheepSaben is a listSaben is a ShrewSaben is a ShrimpSaben is a SilkwormSaben is a SilverfishSaben is a SkinkSaben is a SkunkSaben is a SlothSaben is a SlugSaben is a SmeltSaben is a SnailSaben is a SnakeSaben is a listSaben is a SnipeSaben is a Snow leopardSaben is a Sockeye salmonSaben is a SoleSaben is a SparrowSaben is a Sperm whaleSaben is a SpiderSaben is a Spider monkeySaben is a SpoonbillSaben is a SquidSaben is a SquirrelSaben is a StarfishSaben is a Star-nosed moleSaben is a Steelhead troutSaben is a StingraySaben is a StoatSaben is a StorkSaben is a SturgeonSaben is a Sugar gliderSaben is a SwallowSaben is a SwanSaben is a SwiftSaben is a SwordfishSaben is a SwordtailSaben is a TahrSaben is a TakinSaben is a TapirSaben is a TarantulaSaben is a TarsierSaben is a Tasmanian devilSaben is a TermiteSaben is a TernSaben is a ThrushSaben is a TickSaben is a Titext = open('animals.txt','r').readlines()
a = "Saben is a "
for i in lst:
    pg.write(a+i)
    pg.press("Enter...")
